# -----------------------------------------------------------------------------
# SAMPLE DOCKER COMPOSE FILE FOR LOCAL DEVELOPMENT AND TESTING ONLY
# DO NOT USE IN PRODUCTION OR FOR DEPLOYING SENSITIVE DATA
# -----------------------------------------------------------------------------

version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_docstore
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 5s
      timeout: 5s
      retries: 10