name: Push Docker Image to AWS ECR

on: [push]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: fastapi-document-storage-service

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.amazon-ecr-login.outputs.registry }}
          docker build -t $REGISTRY$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY$ECR_REPOSITORY:$IMAGE_TAG